# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

weapons_list = [
"Baselard",
"Cinquedea",
"Ear dagger",
"GroBes Messer",
"Katar",
"Mercygiver",
"Poniard",
"Rondel",
"Scramasax",
"Sgian",
"Stiletto",
"Dirk",
"Anelace",
"Parrying Dagger",
"Seax",
"Sai (weapon)",
"Swords can be single or double-bladed edges. The blade can be straight or curved.",
"Arming sword",
"Shortsword",
"Zweihander",
"Claymore",
"Longsword",
"Broadsword",
"Falchion",
"Flamberge",
"Sabre",
"Katana",
"Ulfberht",
"Battle axe",
"Club",
"Flail",
"Mace",
"Flanged mace",
"Pernach",
"Shestopyor",
"Maul",
"Morning star",
"Quarterstaff",
"War hammer",
"Bec de Corbin",
"Horseman's pick",
"Bludgeon",
"Horseman's pick",
"Bardiche",
"Bill",
"Glaive",
"Guisarme",
"Halberd",
"Lance",
"Lochaber Axe",
"Lucerne hammer",
"Man catcher",
"Military fork, the weaponized Pitchfork",
"Partisan",
"Pike",
# "Plançon a picot",
"Ranseur",
"Sovnya",
"Spetum",
"Swordstaff",
"Voulge",
"War-scythe",
"War hammer",
"Bombard",
"Bow",
"Longbow",
"English longbow",
"Recurve bow",
"Mongol bow",
"Crossbow",
"Arbalest",
"Ballista",
"Repeating crossbow",
"Sling",
"Throwing Weapons",
"Francisca",
"Nzappa zap",
"Tomahawk",
"Throwing Spear",
"Shuriken",
"Chakram",
"Culverin",
"Musket",
"Battering ram",
"Ballista",
"Catapult",
"Mangonel",
"Onager",
"Petrary",
"Trebuchet",
"Siege Tower",
"Cannon",
"Caravel",
"Carrack",
"Cog",
"Fire ship",
"Hellburners",
"Galleon",
"Galley",
"Junk",
"Longship",
"Lou chuan (castle ship)",
"Qiao chuan (bridge ship)",
"Bailey",
"Battlement",
"Barbican",
"Castle",
"Citadel",
"City wall",
"Curtain wall",
"Drawbridge",
"Fortified tower",
"Gate",
"Keep",
"Moat",
"Motte-and-bailey",
"Murder-hole",
"Palisade",
"Portcullis"]


def get_gladiator(weapons_list)
	Gladiator.create({
		name: Faker::Name.name,
		weapon: weapons_list.sample,
		victory_count: rand(100)
	})
end


100.times do 
	get_gladiator(weapons_list)
end