# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2d92e3ef519d5a8fd285f89174529e9a65a002cecd38186d2fb43ccf85f7d20cbfde423da68f597699114df3b20d3c55060607d2ad154bc509ef8b5493a89dfd

test:
  secret_key_base: 6ce53744ae3beb86ae8c7d7d2929ceac4a0b025f99101026baf9f2521298cc310c7b3ece38b23e56c789fef7a362d5a1554eec136637475e297a39291a0183ee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
