# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fc4effee607168e9922434cc9cc0203922cf0f794abf071643410e411ef1774da7626a3db1f4383dbd8259929dac932d01d144559a9d0410da75e46bee35dff2

test:
  secret_key_base: 7e33ac22257bfdc1068f5f72bbe75fe001dae6521f24015f078db0f5d6399c4003a72e16021e01f8ba355234c025200e026665f5e495225c877e88a2787b647c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
