# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 81a49ba764a22e1d68e5eb6de183f5ff6c296ffc8a836274e6b28ba621fc730f6f86f313038837acf218e2f9c7c83cf3a2091679494041e64a3204cac393f6d9

test:
  secret_key_base: 9723915697b612d6523f93ab99e22a3a892c8d59dbc11eb3eaad5c1eb09f6d6a988398c6094f018bde7d1feffd00f2e7bb9dd4d1cff0a368a3bacfe2eefc47c8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
