# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a8066c595c9ebe2bde4360572b1385f8e9bcadc4176a3ba4820d63a816bccb5b212978391baf2a9d9b9629be13184e14c2be350e1d74c1d2ebfd753627678991

test:
  secret_key_base: 140d55f1add90232406fa04e46461a0d9ab36e9fdf76b1e696fd768d6badd0ec69727aec6735a244d26db3bca9dd10c005838ee472b1047ba95b4bc8e6ea3611

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
