# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 64fbab4968dfca720d1175d2dfd25f96ea20f38ae27c10d1c2fbfb5b98991f28fee39b24cad20b4c3984bf7c0dcfbba762b4aedc023c4125869a10d50a98bb84

test:
  secret_key_base: 75c0cc8f78c41d31e91f364c8446b59f6c204ea4d776be7b32e641385b1801659ba6f3ed2ab7e180d5422bdd14018d4054386e7d6479179f8fc078636e3782d6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
