# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 01d6c89fdfe3dd9f79f0ba438fb3ce1835a79eb7d68018c0cb9b4353610ee9ab65fa2223726d2d854e802ea7cb731813b449aba3f132dccb3cfa1f5f2c959b2e

test:
  secret_key_base: 2105eb859fb379a13e9da9d6345d7bd9383e26d834b13d1380565656fc2944dd221277cff53a25b8b16537845f8e07cf51ad6193cce61674998c47309f0ac955

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
