# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aa9cc7d2ff92553a957ec2df00926157d000a2c8aef1d5155516141426b9381e7d0ea544d11583604c9f8e4f87f7082e5b24a538d6cff8f246b7838949f304c5

test:
  secret_key_base: 199b42d7364e05bcd2908a23f46d4de28e361ae42290089acd07aaaab0f88cdc2f14820967efc3ef66bc9bf3db61b510d3011628a7004f27feed7dc76b810071

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
