# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 921624e2d502a0cb7f231371c6d342c0a66c00b49b4318454baaec7b0d2edecfe73fdde4f932fcd42aa47ce317e4008d5b388548091819e6af902e2722615c79

test:
  secret_key_base: b5b84af000a52cfbda65b455ec13f9b0e8efe3ff859ac6333c60fc071e2c4e6a35fcad3cc93b4e1cc76f8a12d57e17a4253b1d01c4646fa363cc5649c4fea421

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
