# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3577a3dec56cb900c0df9c5ba1c8b47a92e40a765f3982edad54d3ddf3fe22a9121701ddd373c600b41829dc00f4cf5b51a3ee7ee3d9091ec77df20b6aa5d0fc

test:
  secret_key_base: 5bad95f9cef45275aa1e3501ca55ea639574c485f094095c2a4517026c3020052ddaff843c518acbfbdd2b724e3c341e0ef2f91965e3ccb969eacde9bd356c21

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
