# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 59a5fe4aa902b6daa7db1d6f5b89f8d65bba8a41a219e44d616d76951addd2c6295ea0d4a192f80973c0f77ae27882b4ed8125486460ba75a192e2891c79a319

test:
  secret_key_base: 88edf1cc531a79de4d6990fc92356f83b06a0cb290c6d82cb955ccd2fb50f9306f74f40348a33695df615f630ff1a2e8c0f0fa6f5cd3c217702882f032928dbb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
