# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Gladiator.delete_all

@weapons_list = [
"Medieval Dagger[edit]",
"Baselard",
"Cinquedea",
"Ear dagger",
"Großes Messer",
"Katar",
"Mercygiver",
"Poniard",
"Rondel",
"Scramasax",
"Sgian",
"Stiletto",
"Dirk",
"Anelace",
"Parrying Dagger",
"Seax",
"Sai (weapon)",
"Swords[edit]",
"Swords can be single or double-bladed edges. The blade can be straight or curved.",
"Arming sword",
"Shortsword",
"Zweihander",
"Claymore",
"Longsword",
"Broadsword",
"Falchion",
"Flamberge",
"Sabre",
"Katana",
"Ulfberht",
"Blunt or Cleaving Weapons[edit]",
"Battle axe",
"Club",
"Flail",
"Mace",
"Flanged mace",
"Pernach",
"Shestopyor",
"Maul",
"Morning star",
"Quarterstaff",
"War hammer",
"Bec de Corbin",
"Horseman's pick",
"Bludgeon",
"Pick weapons[edit]",
"Horseman's pick",
"Spear and other Polearm and Poleaxe Weapons[edit]",
"Bardiche",
"Bill",
"Glaive",
"Guisarme",
"Halberd",
"Lance",
"Lochaber Axe",
"Lucerne hammer",
"Man catcher",
"Military fork, the weaponized Pitchfork",
"Partisan",
"Pike",
"Plançon a picot",
"Ranseur",
"Sovnya",
"Spetum",
"Swordstaff",
"Voulge",
"War-scythe",
"War hammer",
"Ranged[edit]",
"Bombard",
"Bow",
"Longbow",
"English longbow",
"Recurve bow",
"Mongol bow",
"Crossbow",
"Arbalest",
"Ballista",
"Repeating crossbow",
"Sling",
"Throwing Weapons",
"Francisca",
"Nzappa zap",
"Tomahawk",
"Throwing Spear",
"Shuriken",
"Chakram",
"Culverin",
"Musket",
"Siege engine[edit]",
"Battering ram",
"Ballista",
"Catapult",
"Mangonel",
"Onager",
"Petrary",
"Trebuchet",
"Siege Tower",
"Cannon",
"Warships[edit]",
"Caravel",
"Carrack",
"Cog",
"Fire ship",
"Hellburners",
"Galleon",
"Galley",
"Junk",
"Longship",
"Lou chuan (castle ship)",
"Qiao chuan (bridge ship)",
"Fortification[edit]",
"Medieval fortifications also developed in connection with the weapons that opposed them.",
"Bailey",
"Battlement",
"Barbican",
"Castle",
"Citadel",
"City wall",
"Curtain wall",
"Drawbridge",
"Fortified tower",
"Gate",
"Keep",
"Moat",
"Motte-and-bailey",
"Murder-hole",
"Palisade",
"Portcullis"]

10.times do 
  Gladiator.create({
    name: "#{Faker::Name.first_name} #{Faker::Name.last_name}",
    weapon: @weapons_list.sample,
    victory_count: rand(1..100)
    })
end