# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d31042afa33f66715b30167245853725a2d38fc9f9c0630beb18cd66c4a87f1f301726cf4b47c6630cc82ae90a7fe984594e1fd5b30a3e7a7e85df67d4691d48

test:
  secret_key_base: b8c82b98228608cbd9e4a7923651a3bcf210e28a4e10c083a74dc162b9922e17f104264edf0fd90d2573f1a55cf17cb29e167b17d55fa7002d93acd5730f63bc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
