# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e48e62a2e384592dd7a3177aa196b8d074678178cb5ef549283c5e045a3e52288be337e49cb1bdd096ed59328592ed6e3ead518d6b15e717b1373584586cb3a5

test:
  secret_key_base: 8d2d011fe16b4a744fa6251de8813992b01a717461e67f87be867b3b261d44178e6129054c43162811295e0eafff4a47f2b2b521aa2c74b00a94e923b0f4eff5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
