# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3472d6a4697485c19b211d69246935ff71c9cb6411c4c3fff219ba7502a5233f4034d9941fb9dd1ebea94a53efc5466648ca1a57711107bea4e7b7474f8539c6

test:
  secret_key_base: 2000da5f436fc694993f3f0c372a2f041ee8f40bc2a8aeee3362f3dd0e480e3094c2dd807b355ce92b6c7d306489b61537cc6ee0bee5f6ffb6e28bc7e1296ca6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
