# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 025fe71e5c09627369fb859745b61ae6805938cdb11a2b19082d406877d491294e8e280758b710208cf2860fc6d3fcf86fbd78cd1330c966b06261edb467eda3

test:
  secret_key_base: 8793ca4c17dad4226e0f7b7e65ede3fc64094c177b7b9b624c9df4383982ec042c429cd9789d7891f015e00d6c302afb0361ff30a1cae25b42ff530ec4b2b8c0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
