# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 44d2d200487c55d86e7845de8328c06f7df169175e1b3bd4930c9b608bfe31e1fbce34ad64d71987d07d522bf36ede5281aff0a2f3e62bcbf7dce24e99e33852

test:
  secret_key_base: 85db71ac3bbdb4dded85f7581e7b58d985add56aee5d18e51287cc25879cc6927271cd5f2ab6ba4a2f09d7664ec79102a29a1866345e35b98d13dcf43312f294

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
