# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d65035be48cef7a62f36861a23451497ea371c27907589615716e90cee53a514e29743130ee25d2ff50883f7d11c8ef1da10ed9cae75db5ddcf8dbd84a58acce

test:
  secret_key_base: de0b41c788ba919393868cc4373f525b142e6f850129b784b97a183045d4c37b1569cd06c065550b2801602e49028adc6788d5a3e014c550c24a5d13ba9f6a50

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
