# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c0ec5a93a82860fc4980c2afb1557afaef128ca95142746960620ea65a90238304c86be1c13d5779b258a0bd1884621b72bbaafb2a621d72ae6b64cb130503f8

test:
  secret_key_base: d95e67caa6afa59fced50b315150ec0b5885f2ab3f27c447f8548bfe0983c8b676bb233774e3dab2eb47c9c1a38c6057dd40f6a781e87ae1001f2cf8bee3cd2f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
