# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 92e79e0e43b7e309fde7b034d8ca3a809a48b8ec8756a93a2725903296f5539473ccea4f3aaaf8d2f3fd5707f91a4b5de5992bff1d4e6a2d8faebd741fb1c3df

test:
  secret_key_base: c9ef16723b09183638ac0c83e0dbfa3e029b62af3ae7f39f29623b92c5938d7c904902bf8072d19b6a56356cb4bec697b0da80276f8e935e93308ff9dcb9e1c4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
