# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2ad8f6d1aa693ab043ab447a5f81046e9e8cbf1045544435cc642a0dccf2bb2e1873d8d8949e4649491de5c8eb25cd32edf03bea365745312797008bba599ed5

test:
  secret_key_base: e45537d5f15c88c7a72237d0d1b5a05fba7556ec3047d4de4c4849288c5effdb67a82074aa6c89429a6be20e42c1580e4eea4de95472e7c4bafddbb073c31d71

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
