# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 525aab6a497a208e62d3f041a446c42943a262c54c9ac8a59f97898d6321ee5d479470db86ee0201821f926c74cbbdb1714982545b86523c56cc4e4d4b0f4455

test:
  secret_key_base: 89019cf1493bf25e6c1ace33c3f1a7e883ab7b79dd43b8312f5a598fa7f1a95811f8d37bcdb9924f2484af3580694f56698f0b65532fe33e4eb53ac578f993ba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
