# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 84f9e0ae3288d7f8ff1e0f3798ff05eb216ce143dc31ff2216d895538deb9e24f123d0307007d8c4858afc2d20746c7bdb027183394cc297ff8aa0893143f497

test:
  secret_key_base: 7cfd7994bfa2cb3b908e1467dc46ece9443047acc6d23b2210645411c9fbefe8907e724e95d171b76e3af5705805224a0a91116e40a1345b8930df213e5aeb2f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
